### ISSUE TITLE
[REVIEW] Open Materials Review

### ISSUE THREAD

**Issue by chatchavan** [journalovi/2024-dibartolomeo-benchmark#4]
### Instructions for Open Practices Chair
- If there is anything in the list below that you are unsure of, you can reply to this issue (after it has been created) and tag the responsible organizers. Organizers' Github IDs are listed on [People page](https://www.journalovi.org/people.html).
- If anything in the below list is missing (e.g. required paper sections, supplemental materials, etc), [mention](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams) the authors on this issue and ask them to add those materials. Authors' Github IDs are listed at the top of `README.md`.
- Once authors have provided any missing material (or if no material is missing) and all requirements are met, close this issue.

### Open Materials Checklist
- [ ] Paper license is CC-BY
- [ ] The "Research materials" section in the paper exists.
- [ ] Links to supplements and materials are listed in at least the following locations:
   - [ ] Abstract (according to the [structured abstract requirement](https://www.journalovi.org/author-guide.html#abstract))
   - [ ] "Research materials" section of the paper.
- [ ] All links to repositories and materials in the paper can be reached.
- [ ] All materials are in repositories that meet the [FAIR principles](https://www.go-fair.org/fair-principles/) (e.g. OSF, Zenodo, etc). Non-long-term hosting solutions, such as Github or self-hosted websites, are acceptable only if they are also archived on a long term repository like OSF or Zenodo. One easy way to archive + DOI an existing Github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
- [ ] Check that all other requirements under the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements) are fulfilled.

**Comment by codydunne** [comment]
@mlisnic, @picorana will submit a registration for this.

Below is some food for thought I may write up as a blog post.

A registration sounds good to me in this case because there is no substantial downside if we need OSF to delete the registration later and upload a new one. 

But when the correct timestamp is essential, such as a preregistration, I'm getting more wary about registering many files that weren't as closely manually checked for data that shouldn't be included. It is more difficult to go back and remove or fix any incorrectly included data, e.g., PII, confidential information, or breaks of anonymity.

Working with OSF to get the data removed or cleaned is challenging. They are helpful when asked and have manual processes for fixing the issues, but they are error-prone.

Here is an example of that problem.

We submitted our [Relational Diagrams](https://dunne.dev/pubs/Gatterbauer2024ReasonableEffectiveness/) paper to SIGMOD, including an anonymous link to a controlled experiment preregistration at https://osf.io/4zpsk/. We took great care to avoid revealing our author names, institution, or project name because SIGMOD takes anonymity in supplemental materials extremely seriously. 

However, we made two mistakes in the files we included along with the registration document which could identify us and get our paper desk rejected:
1. One PDF file included my co-author's name in the PDF metadata, automatically included in the PDF generated by PowerPoint.
2. One Markdown file included the name Relational Diagrams in a title, which was already publicly known as the name of our project from a previous preprint, submissions, and presentations. We had elsewhere used a placeholder name.

I emailed OSF, asking them to replace those files with cleaned versions that differed only in that content, not in any semantics. OSF offered to delete our registration and let us submit a new one with a new timestamp. Unfortunately, we have already collected the data, ran our analysis (see https://osf.io/f2xe3), and submitted the paper with a link to our current preregistration. Starting a new preregistration with a current timestamp would defeat the point of registering before collecting data.

OSF replaced the files for us. However, the replacement was only partially correct. The PDF had the correct metadata, both for the web PDF viewer and the file if you download it. However, the Markdown file still had our original title on the web viewer, even if I hard refreshed the page or opened the anonymous link in a private browsing instance. The download link had the corrected version, though. In both cases, the download filename and extension were changed to some long, unique ID.

I wrote to OSF about these issues. They fixed it partially. The OSF web page showed the old version in the web viewer if I used the direct link, even when logging in on a new private browsing instance. But the updated version showed when I used the anonymous peer review link! For both files, the download filename and extension were still changed.

We left the remaining problems as-is because they didn't affect our submission, as everything through the anonymous link worked. But let this serve as a warning to others about registering more than necessary :-).

**Comment by picorana** [comment]
Hi @mlisnic, the registration is available here: [osf.io/v2gqd](https://osf.io/v2gqd).

**Comment by mlisnic** [comment]
Great, thanks! All the requirements are met now so closing the issue.

- [x] Paper license is CC-BY
- [x]  The "Research materials" section in the paper exists.
- [x]  Links to supplements and materials are listed in at least the following locations:
    - [x]  Abstract (according to the [structured abstract requirement](https://www.journalovi.org/author-guide.html#abstract)  
    - [x]  "Research materials" section of the paper.
- [x]  All links to repositories and materials in the paper can be reached.
- [x]  All materials are in repositories that meet the [FAIR principles](https://www.go-fair.org/fair-principles/) (e.g. OSF, Zenodo, etc). Non-long-term hosting solutions, such as Github or self-hosted websites, are acceptable only if they are also archived on a long term repository like OSF or Zenodo. One easy way to archive + DOI an existing Github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
- [x]  Check that all other requirements under the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements) are fulfilled.

**Comment by floe** [comment]
Reopening so that all reviews are visible on the main issue page.
